### ISSUE TITLE
Device orientation

### ISSUE THREAD

**Issue by JFERSD** [skx926/KSGuideController#1]
Hi @skx926 ,

When the device orientation changes the GuideController is not updating properly.

**Comment by Alphts** [comment]
when the demo run in iOS8.0,there are a bug when the first guide show,i think it is because `hollowFrame` is wrong.

**Comment by skx926** [comment]
That's because the convert frame method in iOS 8.0 not working properly, I'll fix this later this week.

**Comment by skx926** [comment]
These 2 bugs has been fixed in version 0.0.3.
