### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by JFERSD** [skx926/KSGuideController#2]
hi @skx926 ,

I've seen that `show()` function checks automatically if the UserDefaults key `guideKey` exists. I would like to manage myself when to load a guide but I can't extend KSGuideController and apply my custom show method due to the access level of the property `private var completion: CompletionBlock?`

Would be interesting to not being forced to used this feature.

**Comment by skx926** [comment]
Actually there is a temporary way to ignore the cache logic:
do not use this `public func show(from vc: UIViewController, completion:CompletionBlock?)` method to show KSGuideController, use `open func present(_ viewControllerToPresent: UIViewController, animated flag: Bool, completion: (() -> Swift.Void)? = nil)` to present it instead.

The disadvantage of using this method is that the completionBlock inside that show method will have nowhere to pass in...

**Comment by JFERSD** [comment]
Thanks @skx926 

I will use the way you suggested.

**Comment by skx926** [comment]
In the new version 0.0.3, you can use show method with nil key to provide your cache logic.
