### ISSUE TITLE
Arrow image nil

### ISSUE THREAD

**Issue by DavidLari** [skx926/KSGuideController#3]
Hi,
Thanks for making and sharing this library. It's exactly what I was looking for. However, when I installed via cocoapods, it crashed trying to force unwrap the arrow image. I was able to resolve it by copying the arrow image to my project. However, this can be corrected by reading the image from the bundle with the framework instead of the main bundle per below.

In my testing it looks like you should be able to change this line in configViews() from:

```
arrowImageView.image = UIImage(named: arrowImageName)?.ks_image(with: arrowColor)
        
```

to:
```
arrowImageView.image = UIImage(named: arrowImageName, in: Bundle(for: KSGuideController.self), compatibleWith: nil)?.ks_image(with: arrowColor)
```

**Comment by skx926** [comment]
Thanks for your advice, I've fix this bug in 0.0.4
